# Use the official Node.js image as a parent image
FROM node:latest

# Copy the package.json and package-lock.json (or yarn.lock if using yarn) to the container
COPY package*.json ./

WORKDIR /web/

COPY . /web/

# Install the project's dependencies inside the container
RUN npm install

RUN npx next build

# Make the container listen on port 3000 (default for Nest.js) at runtime
EXPOSE 3000

# Specify the command to run when the container starts
CMD [ "npm", "run", "start" ]