# Start from the Keycloak base image
FROM quay.io/keycloak/keycloak:22.0.3

# Set environment variables
ENV KEYCLOAK_ADMIN=root
ENV KEYCLOAK_ADMIN_PASSWORD=toor
ENV DB_VENDOR=POSTGRES
ENV DB_ADDR=postgres
ENV DB_DATABASE=mydatabase
ENV DB_USER=root
ENV DB_PASSWORD=toor

# Copy custom configuration file(s)
COPY ./realm-export.json /etc/keycloak/realm-export.json

# Copy entrypoint script
COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]